// The 22 quest definitions. Kept as a code constant rather than a
// Firestore collection for v1.1 — fewer reads per claim, no seed step,
// and tuning is a code change anyway. If we later want hot-tuning we
// can introduce a quest_definitions collection that overrides this.

import type { QuestDefinition, QuestReward } from './questTypes';

const DAILY_REWARD: QuestReward = { coins: 100, shards: 0, keys: 0 };
const WEEKLY_REWARD: QuestReward = { coins: 500, shards: 0, keys: 1 };

const FACTION_GATE = { min_cards_in_faction: 5 };

export const QUEST_DEFINITIONS: QuestDefinition[] = [
  // ─── DAILY POOL (13) ────────────────────────────────────────────────
  {
    quest_id: 'daily_win_matches',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'matches_won',
    target_min: 1,
    target_max: 3,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Win {n} matches today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_win_matches_faction',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'matches_won_with',
    target_min: 1,
    target_max: 2,
    reward: DAILY_REWARD,
    filter: 'faction',
    filter_options: FACTION_GATE,
    title_template: 'Win {n} matches with {faction} today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_play_units',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'units_played',
    target_min: 5,
    target_max: 15,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Play {n} unit cards today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_play_spells',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'spells_played',
    target_min: 3,
    target_max: 8,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Play {n} spell cards today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_play_lane_melee',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'lane_melee_played',
    target_min: 5,
    target_max: 12,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Play {n} cards in the Melee lane today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_play_lane_ranged',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'lane_ranged_played',
    target_min: 5,
    target_max: 12,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Play {n} cards in the Ranged lane today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_play_lane_siege',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'lane_siege_played',
    target_min: 5,
    target_max: 12,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Play {n} cards in the Siege lane today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_summon',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'summons',
    target_min: 1,
    target_max: 3,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Summon {n} cards today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_campaign_stages',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'campaign_stages_won',
    target_min: 1,
    target_max: 2,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Complete {n} campaign stages today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_matches_completed',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'matches_completed',
    target_min: 2,
    target_max: 3,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Complete {n} matches today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_commander_used',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'commander_used_count',
    target_min: 3,
    target_max: 5,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Use your commander ability {n} times today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_win_few_losses',
    period: 'daily',
    tracker_kind: 'conditional_match',
    counter_key: 'wins_with_low_losses',
    target_min: 3,
    target_max: 5,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Win a match without losing more than {n} cards today',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'daily_play_rarity',
    period: 'daily',
    tracker_kind: 'counter',
    counter_key: 'cards_played_rare_or_higher',
    target_min: 3,
    target_max: 5,
    reward: DAILY_REWARD,
    filter: null,
    title_template: 'Play {n} Rare or higher cards today',
    weight: 1,
    is_always_assigned: false,
  },

  // ─── WEEKLY POOL (9) ────────────────────────────────────────────────
  {
    quest_id: 'weekly_streak',
    period: 'weekly',
    tracker_kind: 'streak',
    counter_key: 'streak_days_completed',
    target_min: 6,
    target_max: 6,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Complete all daily quests on {n} of 7 days this week',
    weight: 1,
    is_always_assigned: true,
  },
  {
    quest_id: 'weekly_win_matches',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'matches_won',
    target_min: 15,
    target_max: 15,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Win {n} matches this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_win_matches_faction',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'matches_won_with',
    target_min: 10,
    target_max: 10,
    reward: WEEKLY_REWARD,
    filter: 'faction',
    filter_options: FACTION_GATE,
    title_template: 'Win {n} matches with {faction} this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_play_cards',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'cards_played',
    target_min: 100,
    target_max: 100,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Play {n} cards this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_play_units',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'units_played',
    target_min: 50,
    target_max: 50,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Play {n} unit cards this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_play_spells',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'spells_played',
    target_min: 30,
    target_max: 30,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Play {n} spell cards this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_campaign_stages',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'campaign_stages_won',
    target_min: 5,
    target_max: 5,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Complete {n} campaign stages this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_matches_completed',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'matches_completed',
    target_min: 8,
    target_max: 8,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Complete {n} matches this week',
    weight: 1,
    is_always_assigned: false,
  },
  {
    quest_id: 'weekly_summon',
    period: 'weekly',
    tracker_kind: 'counter',
    counter_key: 'summons',
    target_min: 20,
    target_max: 20,
    reward: WEEKLY_REWARD,
    filter: null,
    title_template: 'Summon {n} cards this week',
    weight: 1,
    is_always_assigned: false,
  },
];

export function getDefinition(quest_id: string): QuestDefinition | null {
  return QUEST_DEFINITIONS.find((d) => d.quest_id === quest_id) ?? null;
}

export function getAllDefinitionsForPeriod(period: 'daily' | 'weekly'): QuestDefinition[] {
  return QUEST_DEFINITIONS.filter((d) => d.period === period);
}
