// scripts/seed-data/campaign_stages.ts
//
// Source of truth for the 54 campaign stages (9 stages × 6 factions).
// Consumed by scripts/seed-firestore.ts (seedCampaignStages), which:
//   - Adds created_at = serverTimestamp() at write time.
//   - Computes opponent_deck_card_ids at seed time by cycling unit cards from
//     the faction's pool in card_library. Phase 7 will hand-tune per-stage decks.
//
// Stage IDs follow `${faction_underscored_lowercase}_${stage_number_padded_2_digits}`.
// Commanders use the actual seeded IDs from Commander_Library.csv:
//   Lane_1 (Melee) = -01, Lane_2 (Ranged) = -02, Lane_3 (Siege) = -03.

import type { CampaignStage } from '../../src/types/campaign';

// Same as CampaignStage but without server-set fields and with the deck list
// left empty (populated at seed time).
export type CampaignStageSeed = Omit<CampaignStage, 'created_at'>;

export const CAMPAIGN_STAGES: CampaignStageSeed[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // VANGUARD KINGDOMS (starter — always unlocked)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    stage_id: 'vanguard_kingdoms_01',
    faction: 'Vanguard Kingdoms',
    stage_number: 1,
    title: 'First Patrol',
    description: 'A routine patrol turns into your first real test of command.',
    difficulty: 'easy',
    opponent_name: 'Bandit Lieutenant',
    opponent_commander_id: 'CMD-VAN-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_02',
    faction: 'Vanguard Kingdoms',
    stage_number: 2,
    title: 'The Cursed Crossing',
    description: 'The enemy has begun using dark magic. Learn to cleanse your lanes.',
    difficulty: 'easy',
    opponent_name: 'Cursed Brigand',
    opponent_commander_id: 'CMD-VAN-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_03',
    faction: 'Vanguard Kingdoms',
    stage_number: 3,
    title: 'Hold the Line',
    description: "A larger force tests your commander's active ability.",
    difficulty: 'easy',
    opponent_name: 'Veteran Sergeant',
    opponent_commander_id: 'CMD-VAN-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_04',
    faction: 'Vanguard Kingdoms',
    stage_number: 4,
    title: 'The Border Skirmish',
    description: 'Standard difficulty. Your tactics must improve.',
    difficulty: 'standard',
    opponent_name: 'Rival Captain',
    opponent_commander_id: 'CMD-VAN-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_05',
    faction: 'Vanguard Kingdoms',
    stage_number: 5,
    title: 'The Siege Begins',
    description: 'A heavy siege force. Plan your back lines carefully.',
    difficulty: 'standard',
    opponent_name: 'Siege Commander',
    opponent_commander_id: 'CMD-VAN-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_06',
    faction: 'Vanguard Kingdoms',
    stage_number: 6,
    title: 'Twilight Patrol',
    description: 'A skilled archer captain meets you at dusk.',
    difficulty: 'standard',
    opponent_name: 'Archer Captain Vell',
    opponent_commander_id: 'CMD-VAN-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_07',
    faction: 'Vanguard Kingdoms',
    stage_number: 7,
    title: 'Lieutenant Marek',
    description: "A renowned knight. He fights with a Vanguard General's discipline.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Marek',
    opponent_commander_id: 'CMD-VAN-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_08',
    faction: 'Vanguard Kingdoms',
    stage_number: 8,
    title: 'Lieutenant Sora',
    description: 'A tactician famed for her precision. Watch your ranged lanes.',
    difficulty: 'standard',
    opponent_name: 'Lieutenant Sora',
    opponent_commander_id: 'CMD-VAN-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'vanguard_kingdoms_09',
    faction: 'Vanguard Kingdoms',
    stage_number: 9,
    title: 'Marshal Aldric — The Final Test',
    description: 'The Marshal himself awaits. Defeat him to prove yourself worthy of the next campaign.',
    difficulty: 'boss',
    opponent_name: 'Marshal Aldric',
    opponent_commander_id: 'CMD-VAN-01',
    opponent_deck_card_ids: [],
    boss_special_rules: {
      commander_pre_activated: true,
      extra_round_draw: 1,
    },
    rewards: { coins: 250, shards: 5, keys: 1 },
    unlocks_factions: ['Iron Pact'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // IRON PACT (unlocks on vanguard_kingdoms_09 win)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    stage_id: 'iron_pact_01',
    faction: 'Iron Pact',
    stage_number: 1,
    title: "The Forge's Welcome",
    description: 'You arrive at the gates of the Iron Pact. They test you.',
    difficulty: 'easy',
    opponent_name: 'Forge Sentinel',
    opponent_commander_id: 'CMD-IRO-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'iron_pact_02',
    faction: 'Iron Pact',
    stage_number: 2,
    title: 'Mountain Pass',
    description: 'Bandits ambush a Pact caravan. Help defend the supply line.',
    difficulty: 'easy',
    opponent_name: 'Forge Master Apprentice',
    opponent_commander_id: 'CMD-IRO-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'iron_pact_03',
    faction: 'Iron Pact',
    stage_number: 3,
    title: 'The Great Anvil',
    description: "A demonstration of the Pact's siege engineering.",
    difficulty: 'easy',
    opponent_name: 'Junior Engineer',
    opponent_commander_id: 'CMD-IRO-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'iron_pact_04',
    faction: 'Iron Pact',
    stage_number: 4,
    title: 'Skirmish at Stonewatch',
    description: 'A border skirmish escalates. Standard tactics no longer work.',
    difficulty: 'standard',
    opponent_name: 'Stonewatch Captain',
    opponent_commander_id: 'CMD-IRO-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'iron_pact_05',
    faction: 'Iron Pact',
    stage_number: 5,
    title: 'The Iron Siege',
    description: "A massive siege force tests your commander's active ability.",
    difficulty: 'standard',
    opponent_name: 'Siege Architect',
    opponent_commander_id: 'CMD-IRO-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'iron_pact_06',
    faction: 'Iron Pact',
    stage_number: 6,
    title: 'Underforge Raid',
    description: 'Raid on the underforge. Watch for ranged ambushes.',
    difficulty: 'standard',
    opponent_name: 'Underforge Warden',
    opponent_commander_id: 'CMD-IRO-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'iron_pact_07',
    faction: 'Iron Pact',
    stage_number: 7,
    title: 'Lieutenant Grom',
    description: "Grom fights with an Iron Lord's relentless aggression.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Grom',
    opponent_commander_id: 'CMD-IRO-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'iron_pact_08',
    faction: 'Iron Pact',
    stage_number: 8,
    title: 'Lieutenant Velka',
    description: "Velka's forge masters strike from precision-built ballistas.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Velka',
    opponent_commander_id: 'CMD-IRO-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'iron_pact_09',
    faction: 'Iron Pact',
    stage_number: 9,
    title: 'High Smith Bregor — Forge of War',
    description: 'The High Smith of the Iron Pact descends from his forge to meet you.',
    difficulty: 'boss',
    opponent_name: 'High Smith Bregor',
    opponent_commander_id: 'CMD-IRO-03',
    opponent_deck_card_ids: [],
    boss_special_rules: {
      // Forge attrition: Bregor draws 2 extra cards per round-end. The forge never stops.
      extra_round_draw: 2,
    },
    rewards: { coins: 250, shards: 5, keys: 1 },
    unlocks_factions: ['Arborea Kingdom', 'Ashen Swarm'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ARBOREA KINGDOM (unlocks on iron_pact_09 win)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    stage_id: 'arborea_kingdom_01',
    faction: 'Arborea Kingdom',
    stage_number: 1,
    title: 'The Verdant Threshold',
    description: 'You enter Arborea. The forest itself watches you.',
    difficulty: 'easy',
    opponent_name: 'Sylvian Scout',
    opponent_commander_id: 'CMD-ARB-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_02',
    faction: 'Arborea Kingdom',
    stage_number: 2,
    title: 'Whispers in the Glade',
    description: 'Druids test your tactics in a sacred grove.',
    difficulty: 'easy',
    opponent_name: 'Glade Druid',
    opponent_commander_id: 'CMD-ARB-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_03',
    faction: 'Arborea Kingdom',
    stage_number: 3,
    title: 'The Thicket Trial',
    description: 'A warden challenges your siege resolve.',
    difficulty: 'easy',
    opponent_name: 'Thicket Apprentice',
    opponent_commander_id: 'CMD-ARB-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_04',
    faction: 'Arborea Kingdom',
    stage_number: 4,
    title: 'Roots of the Ancient Wood',
    description: 'Old growth, older grudges. The forest fights back.',
    difficulty: 'standard',
    opponent_name: 'Ancient Ranger',
    opponent_commander_id: 'CMD-ARB-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_05',
    faction: 'Arborea Kingdom',
    stage_number: 5,
    title: 'The Bramble Citadel',
    description: 'A living fortress of thorns and warden-magic.',
    difficulty: 'standard',
    opponent_name: 'Citadel Warden',
    opponent_commander_id: 'CMD-ARB-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_06',
    faction: 'Arborea Kingdom',
    stage_number: 6,
    title: 'Storm of Arrows',
    description: 'Druids unleash a foresight-driven volley. Cleanse fast.',
    difficulty: 'standard',
    opponent_name: 'High Druid Vael',
    opponent_commander_id: 'CMD-ARB-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_07',
    faction: 'Arborea Kingdom',
    stage_number: 7,
    title: 'Lieutenant Faelara',
    description: 'Faelara strikes with the precision of a sylvian assassin.',
    difficulty: 'standard',
    opponent_name: 'Lieutenant Faelara',
    opponent_commander_id: 'CMD-ARB-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_08',
    faction: 'Arborea Kingdom',
    stage_number: 8,
    title: 'Lieutenant Caelan',
    description: "Caelan's druidic foresight predicts your every play.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Caelan',
    opponent_commander_id: 'CMD-ARB-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'arborea_kingdom_09',
    faction: 'Arborea Kingdom',
    stage_number: 9,
    title: 'Heartwood Warden Lyra — The Living Forest',
    description: 'Lyra calls the forest itself to her aid. Defeat her or be reclaimed by the wild.',
    difficulty: 'boss',
    opponent_name: 'Heartwood Warden Lyra',
    opponent_commander_id: 'CMD-ARB-02',
    opponent_deck_card_ids: [],
    boss_special_rules: {
      starting_lane_buff: { lane: 'Ranged', card_count: 2 },
      extra_round_draw: 1,
    },
    rewards: { coins: 250, shards: 5, keys: 1 },
    unlocks_factions: ['Obsidian Empire', 'Feral Hollow'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ASHEN SWARM (unlocks on iron_pact_09 win — parallel to Arborea)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    stage_id: 'ashen_swarm_01',
    faction: 'Ashen Swarm',
    stage_number: 1,
    title: "The Grave's Edge",
    description: 'The dead stir. You meet them at the boundary of the swarm.',
    difficulty: 'easy',
    opponent_name: 'Crypt Wight',
    opponent_commander_id: 'CMD-ASH-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_02',
    faction: 'Ashen Swarm',
    stage_number: 2,
    title: 'Whispers from the Crypt',
    description: 'Necromancers test your wards. Curses fly thick.',
    difficulty: 'easy',
    opponent_name: 'Apprentice Necromancer',
    opponent_commander_id: 'CMD-ASH-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_03',
    faction: 'Ashen Swarm',
    stage_number: 3,
    title: 'The Dread Procession',
    description: 'A procession of dread knights blocks the path.',
    difficulty: 'easy',
    opponent_name: 'Dread Vanguard',
    opponent_commander_id: 'CMD-ASH-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_04',
    faction: 'Ashen Swarm',
    stage_number: 4,
    title: 'Plague of Bones',
    description: 'The Crypt Lords swell their ranks with each fallen foe.',
    difficulty: 'standard',
    opponent_name: 'Bone Marshal',
    opponent_commander_id: 'CMD-ASH-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_05',
    faction: 'Ashen Swarm',
    stage_number: 5,
    title: 'The Silent Siege',
    description: 'A dread knight siege without horns or war-cries.',
    difficulty: 'standard',
    opponent_name: 'Silent Marshal',
    opponent_commander_id: 'CMD-ASH-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_06',
    faction: 'Ashen Swarm',
    stage_number: 6,
    title: 'Litany of Curses',
    description: 'Necromancer curses fall like rain — cleanse fast or perish.',
    difficulty: 'standard',
    opponent_name: 'High Necromancer Tarn',
    opponent_commander_id: 'CMD-ASH-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_07',
    faction: 'Ashen Swarm',
    stage_number: 7,
    title: 'Lieutenant Korvas',
    description: "Korvas leads the swarm's elite undead vanguard.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Korvas',
    opponent_commander_id: 'CMD-ASH-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_08',
    faction: 'Ashen Swarm',
    stage_number: 8,
    title: 'Lieutenant Ysolde',
    description: "Ysolde's ranged necromancy strikes from impossible distances.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Ysolde',
    opponent_commander_id: 'CMD-ASH-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'ashen_swarm_09',
    faction: 'Ashen Swarm',
    stage_number: 9,
    title: 'Necromancer Vex — Lord of the Crypt',
    description: 'Vex commands the Ashen Swarm itself. The dead obey his every word.',
    difficulty: 'boss',
    opponent_name: 'Necromancer Vex',
    opponent_commander_id: 'CMD-ASH-03',
    opponent_deck_card_ids: [],
    boss_special_rules: {
      commander_pre_activated: true,
      debuff_strength_override: 3,
    },
    rewards: { coins: 250, shards: 5, keys: 1 },
    unlocks_factions: ['Obsidian Empire', 'Feral Hollow'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OBSIDIAN EMPIRE (unlocks on arborea_kingdom_09 OR ashen_swarm_09 win)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    stage_id: 'obsidian_empire_01',
    faction: 'Obsidian Empire',
    stage_number: 1,
    title: 'Embers at the Gate',
    description: 'You approach the obsidian gates. Embers fall like rain.',
    difficulty: 'easy',
    opponent_name: 'Gate Sentinel',
    opponent_commander_id: 'CMD-OBS-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_02',
    faction: 'Obsidian Empire',
    stage_number: 2,
    title: "The Seer's Test",
    description: 'A flame seer reads your intent in the smoke.',
    difficulty: 'easy',
    opponent_name: 'Junior Flame Seer',
    opponent_commander_id: 'CMD-OBS-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_03',
    faction: 'Obsidian Empire',
    stage_number: 3,
    title: "Sky-Tyrant's Watch",
    description: "A sky tyrant's perch tests your aerial defense.",
    difficulty: 'easy',
    opponent_name: 'Sky Sentinel',
    opponent_commander_id: 'CMD-OBS-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_04',
    faction: 'Obsidian Empire',
    stage_number: 4,
    title: 'Ashfall Patrol',
    description: 'Dragonborn warriors patrol the ash plains. They do not parley.',
    difficulty: 'standard',
    opponent_name: 'Ashfall Captain',
    opponent_commander_id: 'CMD-OBS-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_05',
    faction: 'Obsidian Empire',
    stage_number: 5,
    title: "The Tyrant's Roost",
    description: "A sky tyrant's flock descends in wedge formation.",
    difficulty: 'standard',
    opponent_name: 'Roost Tyrant',
    opponent_commander_id: 'CMD-OBS-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_06',
    faction: 'Obsidian Empire',
    stage_number: 6,
    title: "The Pyromancer's Court",
    description: 'Flame seers gather in council. They do not welcome you.',
    difficulty: 'standard',
    opponent_name: 'High Flame Seer',
    opponent_commander_id: 'CMD-OBS-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_07',
    faction: 'Obsidian Empire',
    stage_number: 7,
    title: 'Lieutenant Kazrak',
    description: 'Kazrak is a dragonborn warlord without peer.',
    difficulty: 'standard',
    opponent_name: 'Lieutenant Kazrak',
    opponent_commander_id: 'CMD-OBS-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_08',
    faction: 'Obsidian Empire',
    stage_number: 8,
    title: 'Lieutenant Sylth',
    description: "Sylth's flame seer arts predict every move you make.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Sylth',
    opponent_commander_id: 'CMD-OBS-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'obsidian_empire_09',
    faction: 'Obsidian Empire',
    stage_number: 9,
    title: 'Lord Ignis the Eternal — Crown of Flame',
    description: 'Ignis has worn the obsidian crown for centuries. He does not yield.',
    difficulty: 'boss',
    opponent_name: 'Lord Ignis the Eternal',
    opponent_commander_id: 'CMD-OBS-01',
    opponent_deck_card_ids: [],
    boss_special_rules: {
      starting_lane_buff: { lane: 'Melee', card_count: 2 },
      extra_round_draw: 1,
    },
    rewards: { coins: 250, shards: 5, keys: 1 },
    // Terminal faction — no further unlocks.
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FERAL HOLLOW (unlocks on arborea_kingdom_09 OR ashen_swarm_09 win)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    stage_id: 'feral_hollow_01',
    faction: 'Feral Hollow',
    stage_number: 1,
    title: "The Hollow's Edge",
    description: 'A werewolf alpha tests your right to enter the Hollow.',
    difficulty: 'easy',
    opponent_name: 'Pack Sentinel',
    opponent_commander_id: 'CMD-FER-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_02',
    faction: 'Feral Hollow',
    stage_number: 2,
    title: 'Mire Whispers',
    description: 'Swamp hags murmur curses from the reeds.',
    difficulty: 'easy',
    opponent_name: 'Mire Hag',
    opponent_commander_id: 'CMD-FER-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_03',
    faction: 'Feral Hollow',
    stage_number: 3,
    title: "Beast-Lord's Hunt",
    description: 'A pack of beasts treats you as prey.',
    difficulty: 'easy',
    opponent_name: 'Junior Beast-Master',
    opponent_commander_id: 'CMD-FER-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 50, shards: 0, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_04',
    faction: 'Feral Hollow',
    stage_number: 4,
    title: 'Moon-Driven Pack',
    description: 'Under the full moon, the pack fights without fear.',
    difficulty: 'standard',
    opponent_name: 'Moon Alpha',
    opponent_commander_id: 'CMD-FER-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_05',
    faction: 'Feral Hollow',
    stage_number: 5,
    title: 'Beast-Tide',
    description: 'A tide of beasts threatens to overwhelm every lane.',
    difficulty: 'standard',
    opponent_name: 'Tide Beast-Lord',
    opponent_commander_id: 'CMD-FER-03',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_06',
    faction: 'Feral Hollow',
    stage_number: 6,
    title: "The Hag's Litany",
    description: 'Hag-curses tangle every play. Cleanse or be consumed.',
    difficulty: 'standard',
    opponent_name: 'Elder Hag',
    opponent_commander_id: 'CMD-FER-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 100, shards: 1, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_07',
    faction: 'Feral Hollow',
    stage_number: 7,
    title: 'Lieutenant Thraeg',
    description: 'Thraeg is the alpha of the alpha pack.',
    difficulty: 'standard',
    opponent_name: 'Lieutenant Thraeg',
    opponent_commander_id: 'CMD-FER-01',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_08',
    faction: 'Feral Hollow',
    stage_number: 8,
    title: 'Lieutenant Nessa',
    description: "Nessa's swamp magic warps the very air.",
    difficulty: 'standard',
    opponent_name: 'Lieutenant Nessa',
    opponent_commander_id: 'CMD-FER-02',
    opponent_deck_card_ids: [],
    rewards: { coins: 150, shards: 2, keys: 0 },
  },
  {
    stage_id: 'feral_hollow_09',
    faction: 'Feral Hollow',
    stage_number: 9,
    title: 'Witch-Mother Crone — Roots of Old Magic',
    description: 'The Witch-Mother is older than the Hollow itself. Her magic predates kingdoms.',
    difficulty: 'boss',
    opponent_name: 'Witch-Mother Crone',
    opponent_commander_id: 'CMD-FER-02',
    opponent_deck_card_ids: [],
    boss_special_rules: {
      commander_pre_activated: true,
      debuff_strength_override: 3,
    },
    rewards: { coins: 250, shards: 5, keys: 1 },
    // Terminal faction — no further unlocks.
  },
];
