// scripts/seed-data/expansion_cards.ts
//
// Phase 9.4.2A — 56 new cards (6 Uncommon + 20 Rare + 18 Epic + 12 Legendary)
// that bring per-faction totals to 24 cards (8 Common + 7 Uncommon + 4 Rare +
// 3 Epic + 2 Legendary). Symmetric across the six factions.
//
// Used by scripts/seed-firestore.ts. This file is the single source of truth
// for the new cards' design data — change here, re-run the seed, done.

export type ExpansionCard = {
  card_id: string;
  card_name: string;
  card_type: 'Unit'; // expansion only adds units
  faction: string; // CSV-style with "The " prefix; seed strips it
  rarity: 'Uncommon' | 'Rare' | 'Epic' | 'Legendary';
  base_power: number;
  optimal_lane: 'Melee' | 'Ranged' | 'Siege';
  klass: 'Warrior' | 'Archer' | 'Mage' | 'Healer' | 'Rogue' | 'Behemoth';
  race?: string; // optional override; seed-firestore's resolveRace will fall back
  keywords: string[];
  keyword_params: Record<string, unknown>;
  optimal_lane_bonus?: number; // defaults to 2; Legendaries get 3
  ability_text: string;
  flavor_text: string;
};

export const EXPANSION_CARDS: ExpansionCard[] = [
  // ============== VANGUARD KINGDOMS (9 cards) ==============
  {
    card_id: 'uncommon_vanguard_veteran_sergeant',
    card_name: 'Veteran Sergeant',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Uncommon',
    base_power: 5,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'A grizzled line-holder who steadies the formation.',
    flavor_text: '"I have seen ten battles. I will see ten more."',
  },
  {
    card_id: 'rare_vanguard_banner_knight',
    card_name: 'Banner Knight',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'Rides at the head of every charge, banner held high.',
    flavor_text: 'Where the banner flies, the line does not break.',
  },
  {
    card_id: 'rare_vanguard_crossbow_sergeant',
    card_name: 'Crossbow Sergeant',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Archer',
    keywords: [],
    keyword_params: {},
    ability_text: 'Disciplined volleys delivered by the king\'s sharpshooters.',
    flavor_text: '"On my mark — loose."',
  },
  {
    card_id: 'rare_vanguard_siege_engineer',
    card_name: 'Siege Engineer',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    keywords: [],
    keyword_params: {},
    ability_text: 'Master of trebuchets, mantlets, and the slow art of breaking walls.',
    flavor_text: 'Patience is a weapon. So is a forty-pound stone.',
  },
  {
    card_id: 'epic_vanguard_lord_commander',
    card_name: 'Lord Commander',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: ['rally'],
    keyword_params: { rally: { boost: 2, scope: 'lane' } },
    ability_text: 'Rally: While in play, other allied units in this lane gain +2 power.',
    flavor_text: 'Where he rides, the regiments follow without question.',
  },
  {
    card_id: 'epic_vanguard_trebuchet_master',
    card_name: 'Trebuchet Master',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    keywords: ['cleave'],
    keyword_params: { cleave: { damage: 3 } },
    ability_text: 'Cleave: When played, deal 3 damage to one enemy unit in an adjacent lane.',
    flavor_text: 'A loosed counterweight does not negotiate.',
  },
  {
    card_id: 'epic_vanguard_cathedral_guard',
    card_name: 'Cathedral Guard',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: ['veteran'],
    keyword_params: { veteran: { boost: 1 } },
    ability_text: 'Veteran: At the start of each round, gain +1 base power permanently.',
    flavor_text: 'They have stood the great doors for a hundred winters.',
  },
  {
    card_id: 'legendary_vanguard_marshal_aldric_the_iron_saint',
    card_name: 'Marshal Aldric, the Iron Saint',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Legendary',
    base_power: 9,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    optimal_lane_bonus: 3,
    keywords: ['rally'],
    keyword_params: { rally: { boost: 2, scope: 'global' } },
    ability_text: 'Rally: All other allied Vanguard units in any lane gain +2 power.',
    flavor_text: 'Knighted by three kings. Outlived all three.',
  },
  {
    card_id: 'legendary_vanguard_the_crowned_lion',
    card_name: 'The Crowned Lion',
    card_type: 'Unit',
    faction: 'The Vanguard Kingdoms',
    rarity: 'Legendary',
    base_power: 10,
    optimal_lane: 'Melee',
    klass: 'Behemoth',
    optimal_lane_bonus: 3,
    keywords: ['cleave'],
    keyword_params: { cleave: { damage: 4 } },
    ability_text: 'Cleave: When played, deal 4 damage to the strongest enemy unit in an adjacent lane.',
    flavor_text: 'Crowned by ancient kings. Bowed to none of them.',
  },

  // ============== IRON PACT (10 cards) ==============
  {
    card_id: 'uncommon_iron_pact_forge_apprentice',
    card_name: 'Forge Apprentice',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Uncommon',
    base_power: 4,
    optimal_lane: 'Ranged',
    klass: 'Healer',
    keywords: [],
    keyword_params: {},
    ability_text: 'Tends the bellows, mends the wounded, hauls the iron.',
    flavor_text: 'You learn the hammer before you swing the sword.',
  },
  {
    card_id: 'rare_iron_pact_anvil_bearer',
    card_name: 'Anvil Bearer',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'Carries a forge-anvil into battle and uses it as a shield.',
    flavor_text: '"This anvil shaped my father\'s sword. Now it stops yours."',
  },
  {
    card_id: 'rare_iron_pact_tunnel_sapper',
    card_name: 'Tunnel Sapper',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Siege',
    klass: 'Rogue',
    keywords: [],
    keyword_params: {},
    ability_text: 'Burrows beneath enemy fortifications and brings them down from below.',
    flavor_text: 'The wall fell before the assault began.',
  },
  {
    card_id: 'rare_iron_pact_drillmaster',
    card_name: 'Drillmaster',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'Drills the ranks until they fight as one body.',
    flavor_text: 'Discipline is a forge. Recruits go in soft and come out steel.',
  },
  {
    card_id: 'rare_iron_pact_hearth_spellbinder',
    card_name: 'Hearth Spellbinder',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Channels the heat of the great forges into binding runes.',
    flavor_text: 'The rune burns. The rune binds. The rune holds.',
  },
  {
    card_id: 'epic_iron_pact_master_engineer',
    card_name: 'Master Engineer',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    keywords: ['cleave'],
    keyword_params: { cleave: { damage: 3 } },
    ability_text: 'Cleave: When played, deal 3 damage to one enemy unit in an adjacent lane.',
    flavor_text: 'She built the cannon, the ballista, and the hammer that broke them both.',
  },
  {
    card_id: 'epic_iron_pact_ember_brand',
    card_name: 'Ember Brand',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: ['veteran'],
    keyword_params: { veteran: { boost: 1 } },
    ability_text: 'Veteran: At the start of each round, gain +1 base power permanently.',
    flavor_text: 'A blade quenched in dragon-ash. It remembers every kill.',
  },
  {
    card_id: 'epic_iron_pact_iron_golem',
    card_name: 'Iron Golem',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Epic',
    base_power: 8,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    keywords: [],
    keyword_params: {},
    ability_text: 'Hammered together from rune-bound plate and cold mountain stone.',
    flavor_text: 'It does not tire. It does not yield. It does not feel.',
  },
  {
    card_id: 'legendary_iron_pact_forgemaster_brunhild',
    card_name: 'Forgemaster Brunhild',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Legendary',
    base_power: 9,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    optimal_lane_bonus: 3,
    keywords: ['cleave', 'veteran'],
    keyword_params: {
      cleave: { damage_split: [3, 2] },
      veteran: { boost: 1 },
    },
    ability_text:
      'Cleave: When played, deal 5 damage split between two enemy units in adjacent lanes (3 + 2). Veteran: +1 base power per round.',
    flavor_text: 'She forged the king\'s crown. Then forged a hammer to break it.',
  },
  {
    card_id: 'legendary_iron_pact_the_mountain_king',
    card_name: 'The Mountain King',
    card_type: 'Unit',
    faction: 'The Iron Pact',
    rarity: 'Legendary',
    base_power: 10,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    optimal_lane_bonus: 3,
    keywords: ['veteran', 'rally'],
    keyword_params: {
      veteran: { boost: 1 },
      rally: { boost: 1, scope: 'global', lane_filter: 'Siege' },
    },
    ability_text:
      'Veteran: +1 base power per round. Rally: While in play, allied Iron Pact Siege units gain +1 power.',
    flavor_text: 'The mountains chose him. He never asked.',
  },

  // ============== ARBOREA KINGDOM (9 cards) ==============
  {
    card_id: 'uncommon_arborea_briar_sprite',
    card_name: 'Briar Sprite',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Uncommon',
    base_power: 4,
    optimal_lane: 'Siege',
    klass: 'Rogue',
    keywords: [],
    keyword_params: {},
    ability_text: 'Skitters through thornwood, leaving torn cloaks and bleeding ankles.',
    flavor_text: 'You hear the laughter only after it is gone.',
  },
  {
    card_id: 'rare_arborea_wolfshaper',
    card_name: 'Wolfshaper',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Speaks the old tongue and the wolves answer.',
    flavor_text: 'The pack is hers. The hunt is hers. The forest, hers.',
  },
  {
    card_id: 'rare_arborea_thorn_warden',
    card_name: 'Thorn Warden',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'Bound oath-deep to the briarwall — defends it with every drop of green sap.',
    flavor_text: 'The forest does not need a sword. It has him.',
  },
  {
    card_id: 'rare_arborea_glade_singer',
    card_name: 'Glade Singer',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Healer',
    keywords: [],
    keyword_params: {},
    ability_text: 'Sings the rootsong that knits flesh and bark alike.',
    flavor_text: 'A song heard at sundown can hold back the night itself.',
  },
  {
    card_id: 'epic_arborea_verdant_druid',
    card_name: 'Verdant Druid',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: ['rally'],
    keyword_params: { rally: { boost: 2, scope: 'lane' } },
    ability_text: 'Rally: While in play, other allied units in this lane gain +2 power.',
    flavor_text: 'Where she walks, even the dead wood remembers green.',
  },
  {
    card_id: 'epic_arborea_thornroot_beast',
    card_name: 'Thornroot Beast',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Epic',
    base_power: 8,
    optimal_lane: 'Melee',
    klass: 'Behemoth',
    keywords: ['burn'],
    keyword_params: {
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 2 },
    },
    ability_text:
      'Burn: At end of each round, deal 2 damage to a random enemy unit in this lane.',
    flavor_text: 'Roots drink. Thorns thirst. Blood pays.',
  },
  {
    card_id: 'epic_arborea_moonweaver',
    card_name: 'Moonweaver',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Threads silver moonlight into shielding spellwork.',
    flavor_text: 'She weaves the sky shut, that the moon may stay.',
  },
  {
    card_id: 'legendary_arborea_queen_sylvara_the_greenmother',
    card_name: 'Queen Sylvara, the Greenmother',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Legendary',
    base_power: 9,
    optimal_lane: 'Ranged',
    klass: 'Healer',
    optimal_lane_bonus: 3,
    keywords: ['rally', 'burn'],
    keyword_params: {
      rally: { boost: 2, scope: 'lane' },
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 2 },
    },
    ability_text:
      'Rally: Other allied units in this lane gain +2 power. Burn: At end of each round, deal 2 damage to a random enemy unit in this lane.',
    flavor_text: 'She has worn the green crown longer than any human kingdom has stood.',
  },
  {
    card_id: 'legendary_arborea_the_worldroot',
    card_name: 'The Worldroot',
    card_type: 'Unit',
    faction: 'The Arborea Kingdom',
    rarity: 'Legendary',
    base_power: 10,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    optimal_lane_bonus: 3,
    keywords: ['rally'],
    keyword_params: {
      rally: { boost: 1, scope: 'global', faction_filter: 'Arborea Kingdom' },
    },
    ability_text:
      'Rally: While in play, all other allied Arborea units in any lane gain +1 power.',
    flavor_text: 'Older than the elves. Older than the kings. Possibly older than the world.',
  },

  // ============== ASHEN SWARM (10 cards) ==============
  {
    card_id: 'uncommon_ashen_swarm_hive_drone',
    card_name: 'Hive Drone',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Uncommon',
    base_power: 4,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'A reanimated husk, one of countless drones in the marching swarm.',
    flavor_text: 'It does not remember being a man. It only remembers the hunger.',
  },
  {
    card_id: 'rare_ashen_swarm_carrion_crawler',
    card_name: 'Carrion Crawler',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Siege',
    klass: 'Rogue',
    keywords: [],
    keyword_params: {},
    ability_text: 'Drags itself across battlefields, growing fatter with every kill.',
    flavor_text: 'It comes when the screaming stops.',
  },
  {
    card_id: 'rare_ashen_swarm_spore_drone',
    card_name: 'Spore Drone',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: [],
    keyword_params: {},
    ability_text: 'A bloated husk that bursts into infectious ash when struck.',
    flavor_text: 'Kill it and it spreads. Leave it and it spreads.',
  },
  {
    card_id: 'rare_ashen_swarm_husk_stalker',
    card_name: 'Husk Stalker',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Siege',
    klass: 'Rogue',
    keywords: [],
    keyword_params: {},
    ability_text: 'A patient stalker that wears the skin of yesterday\'s hunter.',
    flavor_text: 'It learned how to walk like you. It learned how to wait.',
  },
  {
    card_id: 'rare_ashen_swarm_wretchcaller',
    card_name: 'Wretchcaller',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Whistles a binding-tone that calls the lesser dead from every grave nearby.',
    flavor_text: 'The wretches always come when called.',
  },
  {
    card_id: 'epic_ashen_swarm_brood_mother',
    card_name: 'Brood Mother',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Behemoth',
    keywords: ['swarm'],
    keyword_params: {
      swarm: {
        token_type: 'drone_token',
        token_power: 2,
        spawn_count: 2,
        spawn_pattern: 'adjacent_lanes',
      },
    },
    ability_text:
      'Swarm: When played, spawn two 2-power Drone tokens in adjacent lanes.',
    flavor_text: 'Every birth a soldier. Every soldier a corpse waiting to march.',
  },
  {
    card_id: 'epic_ashen_swarm_plague_walker',
    card_name: 'Plague Walker',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: ['burn', 'veteran'],
    keyword_params: {
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 2 },
      veteran: { boost: 1 },
    },
    ability_text:
      'Burn: At end of each round, deal 2 damage to a random enemy in this lane. Veteran: +1 base power per round.',
    flavor_text: 'It walks because it cannot die. It cannot die because it walks.',
  },
  {
    card_id: 'epic_ashen_swarm_locust_storm',
    card_name: 'Locust Storm',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Epic',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: ['swarm'],
    keyword_params: {
      swarm: {
        token_type: 'drone_token',
        token_power: 1,
        spawn_count: 3,
        spawn_pattern: 'all_lanes',
      },
    },
    ability_text:
      'Swarm: When played, spawn three 1-power Drone tokens, one in each lane.',
    flavor_text: 'A cloud thick enough to blot the sun and chew the corn.',
  },
  {
    card_id: 'legendary_ashen_swarm_khazgoth_the_hive_king',
    card_name: 'Khazgoth, the Hive King',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Legendary',
    base_power: 10,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    optimal_lane_bonus: 3,
    keywords: ['swarm', 'veteran'],
    keyword_params: {
      swarm: {
        token_type: 'drone_token',
        token_power: 2,
        spawn_count: 2,
        spawn_pattern: 'adjacent_lanes',
      },
      veteran: { boost: 1 },
    },
    ability_text:
      'Swarm: When played, spawn two 2-power Drone tokens in adjacent lanes. Veteran: +1 base power per round.',
    flavor_text: 'A crown of skulls. A throne of skulls. A kingdom of skulls.',
  },
  {
    card_id: 'legendary_ashen_swarm_the_devouring_tide',
    card_name: 'The Devouring Tide',
    card_type: 'Unit',
    faction: 'The Ashen Swarm',
    rarity: 'Legendary',
    base_power: 9,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    optimal_lane_bonus: 3,
    keywords: ['burn'],
    keyword_params: {
      burn: { target_scope: 'global', target_filter: 'random_enemy', damage: 3 },
    },
    ability_text:
      'Burn: At end of each round, deal 3 damage to a random enemy unit in any lane.',
    flavor_text: 'The tide rose. The tide rolled. The tide ate.',
  },

  // ============== OBSIDIAN EMPIRE (9 cards) ==============
  {
    card_id: 'uncommon_obsidian_empire_cultist_acolyte',
    card_name: 'Cultist Acolyte',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Uncommon',
    base_power: 4,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: ['ritual'],
    keyword_params: { ritual: { mode: 'optional_single' } },
    ability_text:
      'Ritual: When played, you may sacrifice an allied unit. Add its base power to this card.',
    flavor_text: 'The first cut is always your own. The second is always someone else\'s.',
  },
  {
    card_id: 'rare_obsidian_empire_wraithbinder',
    card_name: 'Wraithbinder',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Chains the restless dead into iron-bound service.',
    flavor_text: 'A wraith bound is a soldier owed.',
  },
  {
    card_id: 'rare_obsidian_empire_bonewright',
    card_name: 'Bonewright',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: ['ritual'],
    keyword_params: { ritual: { mode: 'optional_single' } },
    ability_text:
      'Ritual: When played, you may sacrifice an allied unit. Add its base power to this card.',
    flavor_text: 'Every bone has a song. He knows them all by name.',
  },
  {
    card_id: 'rare_obsidian_empire_shadow_whisperer',
    card_name: 'Shadow Whisperer',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Siege',
    klass: 'Rogue',
    keywords: [],
    keyword_params: {},
    ability_text: 'Listens at the edge of dreams and brings back the worst of them.',
    flavor_text: 'You hear her once. You never sleep clean again.',
  },
  {
    card_id: 'epic_obsidian_empire_voidcaller',
    card_name: 'Voidcaller',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: ['burn', 'ritual'],
    keyword_params: {
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 2 },
      ritual: { mode: 'optional_single' },
    },
    ability_text:
      'Ritual: You may sacrifice an allied unit on play to add its base power. Burn: 2 damage to a random enemy in this lane each round.',
    flavor_text: 'She opened the door. The door is always open now.',
  },
  {
    card_id: 'epic_obsidian_empire_dread_knight',
    card_name: 'Dread Knight',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Warrior',
    keywords: ['veteran'],
    keyword_params: { veteran: { boost: 1 } },
    ability_text: 'Veteran: At the start of each round, gain +1 base power permanently.',
    flavor_text: 'His armor is older than the empire. So is the silence inside it.',
  },
  {
    card_id: 'epic_obsidian_empire_hellfire_drake',
    card_name: 'Hellfire Drake',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Epic',
    base_power: 8,
    optimal_lane: 'Melee',
    klass: 'Behemoth',
    keywords: ['burn'],
    keyword_params: {
      burn: { target_scope: 'lane', target_filter: 'all_enemies', damage: 3 },
    },
    ability_text: 'Burn: At end of each round, deal 3 damage to ALL enemy units in this lane.',
    flavor_text: 'The breath is the warning. The fire is the promise.',
  },
  {
    card_id: 'legendary_obsidian_empire_vexarion_the_black_tyrant',
    card_name: 'Vexarion, the Black Tyrant',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Legendary',
    base_power: 10,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    optimal_lane_bonus: 3,
    keywords: ['burn', 'veteran'],
    keyword_params: {
      burn: { target_scope: 'global', target_filter: 'random_enemy', damage: 5 },
      veteran: { boost: 1 },
    },
    ability_text:
      'Burn: At end of each round, deal 5 damage to a random enemy unit in any lane. Veteran: +1 base power per round.',
    flavor_text: 'He razed the seven cities and built the eighth from their stones.',
  },
  {
    card_id: 'legendary_obsidian_empire_the_unmade',
    card_name: 'The Unmade',
    card_type: 'Unit',
    faction: 'The Obsidian Empire',
    rarity: 'Legendary',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    optimal_lane_bonus: 3,
    keywords: ['ritual'],
    keyword_params: { ritual: { mode: 'all_in_lane', power_per_sacrifice: 3 } },
    ability_text:
      'Ritual: When played, sacrifice all other allied units in this lane. Gain +3 base power for each.',
    flavor_text: 'He gave back his name to the dark and was given everything else.',
  },

  // ============== FERAL HOLLOW (9 cards) ==============
  {
    card_id: 'uncommon_feral_hollow_bone_fetishist',
    card_name: 'Bone Fetishist',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Uncommon',
    base_power: 4,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Wears the bones of every kill — the more bones, the louder the magic.',
    flavor_text: 'The dead pay rent in power.',
  },
  {
    card_id: 'rare_feral_hollow_marshhag',
    card_name: 'Marshhag',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: [],
    keyword_params: {},
    ability_text: 'Knows every drowning-pool and every old curse buried in the mud.',
    flavor_text: 'The marsh keeps her secrets. She keeps the marsh.',
  },
  {
    card_id: 'rare_feral_hollow_the_hooded_one',
    card_name: 'The Hooded One',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Siege',
    klass: 'Rogue',
    keywords: ['ritual'],
    keyword_params: { ritual: { mode: 'optional_single' } },
    ability_text:
      'Ritual: When played, you may sacrifice an allied unit. Add its base power to this card.',
    flavor_text: 'Nobody knows what is under the hood. Nobody who saw is left to tell.',
  },
  {
    card_id: 'rare_feral_hollow_pyre_tender',
    card_name: 'Pyre Tender',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Rare',
    base_power: 6,
    optimal_lane: 'Ranged',
    klass: 'Healer',
    keywords: ['burn'],
    keyword_params: {
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 1 },
    },
    ability_text:
      'Burn: At end of each round, deal 1 damage to a random enemy unit in this lane.',
    flavor_text: 'She tends the flame the way mothers tend their young.',
  },
  {
    card_id: 'epic_feral_hollow_blood_witch',
    card_name: 'Blood Witch',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    keywords: ['burn', 'ritual'],
    keyword_params: {
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 2 },
      ritual: { mode: 'optional_single' },
    },
    ability_text:
      'Ritual: You may sacrifice an allied unit on play to add its base power. Burn: 2 damage to a random enemy in this lane each round.',
    flavor_text: 'Blood for blood. Bone for bone. Debt always paid in full.',
  },
  {
    card_id: 'epic_feral_hollow_antler_shaman',
    card_name: 'Antler Shaman',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Ranged',
    klass: 'Healer',
    keywords: ['rally'],
    keyword_params: { rally: { boost: 2, scope: 'lane' } },
    ability_text: 'Rally: While in play, other allied units in this lane gain +2 power.',
    flavor_text: 'The antlers grow longer with every winter she walks.',
  },
  {
    card_id: 'epic_feral_hollow_wretchspawn',
    card_name: 'Wretchspawn',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Epic',
    base_power: 7,
    optimal_lane: 'Melee',
    klass: 'Behemoth',
    keywords: ['swarm', 'veteran'],
    keyword_params: {
      swarm: {
        token_type: 'wretchling_token',
        token_power: 2,
        spawn_count: 2,
        spawn_pattern: 'this_lane',
      },
      veteran: { boost: 1 },
    },
    ability_text:
      'Swarm: When played, spawn two 2-power Wretchling tokens in this lane. Veteran: +1 base power per round.',
    flavor_text: 'It does not parent the brood. It IS the brood.',
  },
  {
    card_id: 'legendary_feral_hollow_mother_vasha_the_crone_of_ten_names',
    card_name: 'Mother Vasha, the Crone of Ten Names',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Legendary',
    base_power: 9,
    optimal_lane: 'Ranged',
    klass: 'Mage',
    optimal_lane_bonus: 3,
    keywords: ['burn', 'ritual'],
    keyword_params: {
      burn: { target_scope: 'global', target_filter: 'random_enemy', damage: 3 },
      ritual: { mode: 'optional_single' },
    },
    ability_text:
      'Ritual: You may sacrifice an allied unit on play to add its base power. Burn: 3 damage to a random enemy in any lane each round.',
    flavor_text: 'She has a name for every age she has lived. There are more names left.',
  },
  {
    card_id: 'legendary_feral_hollow_the_hungering_hollow',
    card_name: 'The Hungering Hollow',
    card_type: 'Unit',
    faction: 'The Feral Hollow',
    rarity: 'Legendary',
    base_power: 9,
    optimal_lane: 'Siege',
    klass: 'Behemoth',
    optimal_lane_bonus: 3,
    keywords: ['swarm', 'burn'],
    keyword_params: {
      swarm: {
        token_type: 'wretchling_token',
        token_power: 3,
        spawn_count: 2,
        spawn_pattern: 'adjacent_lanes',
      },
      burn: { target_scope: 'lane', target_filter: 'random_enemy', damage: 2 },
    },
    ability_text:
      'Swarm: When played, spawn two 3-power Wretchling tokens in adjacent lanes. Burn: 2 damage to a random enemy in this lane each round.',
    flavor_text: 'The Hollow is hungry. The Hollow is always hungry.',
  },
];
